[base]
package = metroid_ii
env_name = metroid_ii
policy_name = Policy
# Recurrent
rnn_name = Recurrent


# Try something like:
# num_envs = 32
# num_workers = 4
# env_batch_size = 16

# Do not set batch_size=1. That is the total number of train steps per update.
# Should be at least 1024, probably at least 4096.  num_envs*128 is a good
# baseline and increase from there. Minibatch size default to 1/4 or 1/8 of that


[train]
# I don't have a GPU on my laptop
device = cuda
# device = cpu

# My oldass GPU can't handle the faster compiled stuff.
compile = False

# total_timesteps = 15_000_000
total_timesteps = 30_000_000

# FOR SWEEPS IM DOING LESS
# with 4k minibatch size, this will really only do 25ish updates
# total_timesteps = 100_000

# How many times to train on each minibatch
# Usually no more than 4 or 5
update_epochs = 3

# Determines refers to "how many steps into the future the agent cares about the
# reward it can receive" 
# Horizon = (batch size / (num envs * num workers))

# How many environments to run in parallel
num_envs = 4

# How many threads to use, very system dependent
num_workers = 4

# 8192
# 16384
# 32768
# 65536

# how many steps of play per update
# batch_size = 32768
batch_size = 16384

# typically 1/4 or 1/8 of batch_size according to J. Saurez
# minibatch_size = 8192
minibatch_size = 2048

# checkpoint every N updates
checkpoint_interval = 50
# FOR SWEEP (probably could just not store any)
# checkpoint_interval = 25

# Vectorization param, see what makes it run fastest
# this is the "pop from empty list" of workers error
# Must be divisible by num_envs/num_workers
env_batch_size = 4

zero_copy = True
gamma = 0.9975
learning_rate = 2.5e-4
anneal_lr = False


