[base]
package = metroid_ii
env_name = metroid_ii
policy_name = Policy
# Recurrent
rnn_name = Recurrent



# Try something like:
# num_envs = 32
# num_workers = 4
# env_batch_size = 16

# Do not set batch_size=1. That is the total number of train steps per update.
# Should be at least 1024, probably at least 4096.  num_envs*128 is a good
# baseline and increase from there. Minibatch size default to 1/4 or 1/8 of that




[train]
# I don't have a GPU
device = cpu
compile = True

total_timesteps = 1_000_000
# How many times to train on <total_timesteps> samples (?)
update_epochs = 10

num_envs = 32
num_workers = 4

# how many steps of play per update (?j
batch_size = 4096

# typically 1/4 or 1/8 of batch_size according to J. Saurez
minibatch_size = 1024

# if N will checkpoint every N updates
checkpoint_interval = 100

# this is the "pop from empty list" of workers error
# Must be divisible by num_envs/num_workers
env_batch_size = 16



zero_copy = True
gamma = 0.998

learning_rate = 3.5e-4
anneal_lr = False

